jwt:
  secretKey: ${JWT_SECRETKEY}
  refreshKey: ${JWT_REFRESHKEY}



spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MYSQL_HOST}:${MYSQL_PORT}/${DATA_BASE_NAME}?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_PASSWORD}
