jwt:
  secretKey: ${JWT_SECRETKEY}
  refreshKey: ${JWT_REFRESHKEY}



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DATA_BASE_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true